### ISSUE TITLE
serif font on home page

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#12]
Wondering why Sentinel is showing up funny like this -- looks squished and kerned weird and it isn't pulling a name in the CSS viewer -- see attached screenshot.
![screen shot 2018-03-13 at 12 26 30 pm](https://user-images.githubusercontent.com/4765127/37365166-f1cc2d72-26b9-11e8-8224-f9135cd48efa.png)

**Comment by pollardld** [comment]
@sarahmagrish 

The font family is empty because the theme wont allow a custom input for typography settings, but the can be left empty. Because they are empty we can set font family to the body of the html in [Custom CSS](http://63y.ea8.mwp.accessdomain.com/wp-admin/themes.php?page=fw-settings) which applies our font all at once. 

The kerning was being applied from the [Typography Settings](http://63y.ea8.mwp.accessdomain.com/wp-admin/themes.php?page=fw-settings). The font family was empty but there was negative letter spacing being applied. I removed all letter spacing should now look good.
