### ISSUE TITLE
tenant page styling

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#23]
Looking at this page here: http://63y.ea8.mwp.accessdomain.com/project/tenant-one/

I know we talked about this portfolio type of page as being less flexible than the other ones but hoping we can do some styling. We need to use this kind of page in order to build a clickable gallery on the main hub page correct? 

My main styling questions are as follows:

Can we change the top breadcrumb to simply "Back to Hub" with a backwards pointing arrow, in Avenir heavy, red color?

Then can we add in padding on the left and right sides of the main text block so the line length is more manageable to read? I think the line length should be a little more than half as long as it is now.

Also wondering if I can add in font size and line height tags to the text viewer for that page and if so how to write them? I'd like to make the font somewhat bigger.

Finally, in the project gallery section is there a way to get rid of that green circle with arrows that appears on mouse over? And can we caption the images in any way?

Let me know if this is unclear / not doable.

thank you!!

**Comment by pollardld** [comment]
@sarahmagrish Answers to questions above:  

  - **We need to use this kind of page in order to build a clickable gallery on the main hub page correct?**  
  A portfolio page is needed in order to build a filter function such as the [one on the haven demo](http://jkj.c37.mwp.accessdomain.com/?page_id=13). 

  - **Can we change the top breadcrumb to simply "Back to Hub" with a backwards pointing arrow, in Avenir heavy, red color?** 
  Not using the theme options, but i can build that in

  - **Then can we add in padding on the left and right sides of the main text block so the line length is more manageable to read?** 
  I can add that through custom css. for sure needed.

  - **Also wondering if I can add in font size and line height tags to the text viewer for that page and if so how to write them? I'd like to make the font somewhat bigger.**
  We can create some new classes e.g. `class="font-size-36"` for 36px text. OR use the Unyson short codes by selecting the U icon from the text editor box:  <img width="303" alt="screen shot 2018-03-23 at 12 34 53 pm" src="https://user-images.githubusercontent.com/2632164/37849969-dcf80cc4-2e96-11e8-992c-3cfb726da565.png">

  - **Finally, in the project gallery section is there a way to get rid of that green circle with arrows that appears on mouse over? And can we caption the images in any way?**
  Unfortunately this does not look to be customizable. The portfolio options can be found under Appearance -> Theme Settings -> Posts -> Portfolio  <img width="400" alt="screen shot 2018-03-23 at 12 41 55 pm" src="https://user-images.githubusercontent.com/2632164/37850252-b6c5f27c-2e97-11e8-90d7-3490b0c94ac1.png">

**Comment by sarahmagrish** [comment]
loving the Unyson short codes -- thanks! Did you maybe already shorten up the line length? I added in a button and header text and was trying to figure out how to get them to all line up: 

http://63y.ea8.mwp.accessdomain.com/project/tenant-one/

I checked the custom CSS area but couldn't spot it.
