### ISSUE TITLE
footer styling

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#26]
Hi David, I think I got the footer as far as I can by myself. Can you help me by adding padding to the columns and removing the red underline from "Upcoming event"? I don't know how it got there. 

Can you also make "redd@ecotrust.org" have a red underline with some space between the word and the underline and the font be avenir heavy? 

Also having trouble getting the serif font down there to all be the same size -- can you even those up?

Any finally finishing up the enews styling for the footer? thanks!

**Comment by pollardld** [comment]
yes to all questions and working on this next

**Comment by pollardld** [comment]
style updates made, let me know if you have any changes. @sarahmagrish 

upcoming events was underlined because it was linking to the home page. So wordpress thought it was the current page menu item and underlined it (like we do in the top nav). the underline is gone now, but just wanted to let you know why it happened in case this issue pops up again in the future.

**Comment by sarahmagrish** [comment]
LOOKING GREAT! oops caps lock. thx
