### ISSUE TITLE
hub page

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#53]
The individual tenant squares are all showing up selected on page load, making them difficult to read

**Comment by pollardld** [comment]
Looks real bad. The only reason I can think of why the theme has overlays shown on touch screen is because on touch screens hover states will intercept the a tap. What i mean by that is that the link to the page for, for purpose of example, B-Line would take two tap:  

  - 1st tap would show the overlay
  - 2nd tap would go to the B-Line page

This is behavior is not bad, but it does cause confusion or frustration in certain implementations.

That gives us two easy choices:

  1. overwrite what the theme has done to force show overlays on touch screens and then use the browser default hover state. requiring two taps to follow a link. which would look like:
    **first tap**:   
    <img width="250" alt="screen shot 2018-05-01 at 2 09 13 pm" src="https://user-images.githubusercontent.com/2632164/39493916-6179923a-4d49-11e8-92aa-78323b820390.png">
    **second tap**:  
    <img width="250" alt="screen shot 2018-05-01 at 2 09 41 pm" src="https://user-images.githubusercontent.com/2632164/39493921-640de0b4-4d49-11e8-8f18-257f0c3ae127.png">
 
  2. use the force show overlay to our advantage and style that. Which could look like this:
    <img width="300" alt="screen shot 2018-05-01 at 2 08 19 pm" src="https://user-images.githubusercontent.com/2632164/39493854-28ca2102-4d49-11e8-83f7-69f42d111a9c.png">

I implemented option 2 for now, but will update with your preference @sarahmagrish

**Comment by sarahmagrish** [comment]
I like it! Thanks David
